Multiprocessing added
ShaharGottlieb/MasseyRamanujan pull request #14
Opened 2021-04-06 13:17 UTC by rotelimelech

* splitting the domain under poly_domains, and spawn a new enumerator for each chunk, under a different process
* each enumerator will only do the first enumeration. The refining is done in a single process
* to allow us to move actions from the second stage to the first (like calculating initial hits to a higher dept), I've added `multiprocessed_find_initial_hits` and `multiprocessed_refine_results` to the abstract enumerator
** in multiprocessed_find_initial_hits Im calling an "addtions" function, that allows child enumerators to add functionality to the first stage
** multiprocessed_refine_results completes this idea by discarding those actions form the second stage

2021-04-12 11:30 UTC, rotelimelech commented
After your comments, i've changed the first and second step without adding abstract functions.
You're right, it looks much cleaner that way :)

2021-04-19 05:06 UTC, ShaharGottlieb requested changes
overall nice job!
small fixes and i'll approve

2021-04-19 05:06 UTC, ShaharGottlieb commented on ramanujan/poly_domains/CartesianProductPolyDomain.py
> +	def split_domains_to_processes(self, number_of_instances):
please add a unit test for this function, making sure that the split is done correctly - 
all elements exist in some partition, and  no more than the total number of elements expected

2021-05-04 10:50 UTC, rotelimelech commented on ramanujan/multiprocess_enumeration.py
> +            deepcopy(lean_lhs.bloom),
it happens automatically, i've removed it

2021-05-07 06:49 UTC, ShaharGottlieb approved these changes

2021-05-07 06:50 UTC, merged